/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package terceiro.desafio;

public class ThirdChallenge {

    public static void main(String[] args) {
        System.out.println();
    }
}
